# Generated by Django 6.0.4 on 2026-04-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='database_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='subdomain',
            field=models.SlugField(default='default', help_text="Subdomain for the school (e.g., 'school1')", unique=True),
            preserve_default=False,
        ),
    ]
