# Generated by Django 6.0.4 on 2026-05-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_remove_student_user_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='guardian_email',
            new_name='father_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='guardian_phone',
            new_name='father_mobile',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='guardian_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='guardian_occupation',
            new_name='father_occupation',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='permanent_address',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
