# Generated by Django 6.0.5 on 2026-06-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school_about_description_school_established_year_and_more'),
        ('schools', '0009_remove_teacher_department_stream_teacher_stream_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='core.school'),
        ),
    ]
